" Basic runtime settings
set nocompatible
syntax on

" Vundle
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

"""""""""""
" Plugins "
"""""""""""
Plugin 'tpope/vim-fugitive'
Plugin 'ervandew/supertab'
Plugin 'scrooloose/nerdtree'
Plugin 'norm2782/vim-clean'
Plugin 'godlygeek/tabular'
Plugin 'plasticboy/vim-markdown'
Plugin 'wesQ3/vim-windowswap'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

" Basic editor settings
set cpoptions+=$
set virtualedit=all
set wildmenu
" Display linenumbers
set number
" Set case insensitive searching
set ic
" Always display at least 6 lines above and below the cursor
set scrolloff=50

" Set tabsize = 4 and various tab options
set tabstop=4
set shiftwidth=4
set softtabstop=4
set smarttab
set expandtab
set autoindent

let mapleader = "\\"

" Map case sensitive commands (because Derp)
:command WQA wqa
:command WQa wqa
:command Wqa wqa
:command WQ wq
:command Wq wq
:command W  w
:command Q  q
:command Qa qa
:command QA qa

" Map F1 to Esc
map <F1> <Esc>
imap <F1> <Esc>
nmap <F1> <Esc>

" Repeat colon (:) command on comma
map , @:<CR>

" YouCompleteMe settings
let g:SuperTabDefaultCompletionType = 'context'

" UltiSnips settings
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<tab>"
let g:UltiSnipsJumpBackwardTrigger="<s-tab>"
let g:UltiSnipsEditSplit="horizontal"

" Filetype mappings
au BufNewFile,BufRead *.ino set filetype=cpp
au BufNewFile,BufRead *.tpp set filetype=cpp

" Highlight setyp 
set colorcolumn=80
au BufNewFile,BufRead *.icl set colorcolumn=140
au BufNewFile,BufRead *.html set colorcolumn=120
au BufNewFile,BufRead *.cpp,*.c,*.h,*.hpp set colorcolumn=110
highlight ColorColumn ctermbg=darkgray

" Open h and hpp includes for clang
let &path.="/usr/include/"

" clang options
let g:clang_c_options = '-std=gnu11'
let g:clang_cpp_options = '-std=c++11 -stdlib=libstdc++ -I/usr/include'
let g:clighter_libclang_file = '/usr/lib/llvm-3.6/lib/libclang.so'

" Config make options
set makeprg=make

" Relative AND absolute line numbers
set relativenumber
set number
