#! /bin/bash

fname=$1
words=$(<$fname)

outf=$2
rm $outf

strlen=$3

prev2=
prev1=

echo "Processing $fname into $outf with max length $strlen"

for word in $words; do
    # Words should not be longer then strlen
    if [[ ${#word} -ge $strlen ]]; then
        word=
    fi

    # Words should not contain special characters or capitals
    if [[ ! $word =~ ^[a-z]+$ ]]; then
        word=
    fi

    # Words should not be subsets of eachother
    if [[ $prev1 == $prev2*  && ! -z $prev1 && ! -z $prev2 ]]; then
        if [[ $word == $prev1* ]]; then
            word=
        else
            prev2=
        fi
    fi

    if [[ -z $word ]]; then
        continue;
    fi
    if [[ -z $prev1 ]]; then
        prev1=$word
        continue;
    fi

    if [[ -z $prev2 ]]; then
        prev2=$prev1
        prev1=$word
        continue;
    fi

    echo $prev2 >> $outf
    prev2=$prev1
    prev1=$word
done
